To-Do List with Javascript
sergioobolevich/To-Do-JS pull request #1
Opened 2021-02-03 22:55 UTC by chubaquelo

In this branch, I have created the basement for a complete To-Do List application.
Projects and Tasks can be added, as well as due dates for tasks and priority (low, medium, or high).
You can open a task by clicking on its name to see description details and modify it.

I have used 2 modules: one for tasks and one for projects.
LocalStorage was implemented to persist changes.

2021-02-04 06:31 UTC, peterrobert requested changes
### CHANGES REQUIRED ♻️ 🛑 
Hello, @chubaquelo very nice work. I love the design. You have done a good job so far. Now let's make it even better. Kindly check the following improvements to be made ⬇️ 

- [ ]  Kindly remove commented code. In your toDoModule.js there is some commented code. This will keep your project clean.
- [ ]  Kindly remove the node_modules in your project. I can see you have added it to the gitignore. But still, the node_modules were pushed to your repo. Kindly fix this.

![lock_files_requirement (1)](https://user-images.githubusercontent.com/32361963/106853151-4c08bc80-66ca-11eb-8e64-9e25a00b3e33.png)

- [ ] Kindly separate your dom-manipulation from your logic. I can see you have two separate modules. However, both have logic and dom-manipulation. Kindly separate the two

![modules_requirement (1)](https://user-images.githubusercontent.com/32361963/106853352-9ee27400-66ca-11eb-8b8b-c4d5f1c9520d.png)

- [ ] I can see your project uses webpack 👏🏿 . However, you have not configured the scripts well in your package.json. Kindly check below ⬇️ 
`
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
  },

`
Just like you see above, your package.json should be configured in such away.

### [OPTIONAL]

- [ ] Kindly add validations to your forms. At the moment a user can create empty projects and to do's.


### if you have any question, kindly reach me on slack @peterrobert

### HAPPY CODING 💻

2021-02-06 09:08 UTC, christianotieno requested changes
## Changes Required ♻️ 
Hello @chubaquelo 👋 

Kindly take a look at some of the issues I have highlighted below based on my review. 
They are based on some elements in the page that ought to be removed as they are confusing.

### Happy coding 💻 
#### Christian Otieno (CR) :octocat:

2021-02-06 09:08 UTC, christianotieno commented on dist/index.html
> +      <select id="select-project"></select>
## Remove unnecessary fields
- [ ] Kindly remove unnecessary busy elements on the page to make it less busy. 
- [ ] The `add new task` below the project is unnecessary as the functionality has been implemented in the form up above. Kindly remove it.
- [ ] The `show` and `order by` fields in the top need also to be removed for the same reason.
![Screenshot 2021-02-06 115510](https://user-images.githubusercontent.com/22345961/107113971-8b264180-6873-11eb-9a6c-1b72275bc616.png)

2021-02-06 09:08 UTC, christianotieno commented on dist/style.css
> +
## Remove Commented out code
- [ ] Comments: It’s better to delete **commented piece of codes**. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

2021-02-08 18:19 UTC, Spayco approved these changes
# Project Approved

thank you for making the required changes, your project is now approved!

### please don't forget to merge to master, good luck with the next projects!


Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2021-02-08 18:21 UTC, merged